# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r: devel
dist: trusty
sudo: required
cache: packages

before_install:
  - sudo add-apt-repository -y ppa:opencpu/jq
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install -y libjq-dev

r_github_packages:
  - SymbolixAU/googleway
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov(type = "all")'
